### ISSUE TITLE
redeployed today for development testing of new version

### ISSUE THREAD

**Issue by webcoderz** [sudograph/sudograph#124]
built and deployed the optimized version, open playground to play with queries and am receiving this error:
{
  "message": "Query failed:\n  Status: rejected\n  Message: IC0302: Canister ryjl3-tyaaa-aaaaa-aaaba-cai has no query method 'graphql_query'\n",
  "stack": "Error: Query failed:\n  Status: rejected\n  Message: IC0302: Canister ryjl3-tyaaa-aaaaa-aaaba-cai has no query method 'graphql_query'\n\n    at caller (http://localhost:8000/_snowpack/pkg/sudograph/build/sudo-playground.js:60935:27)\n    at async query (http://localhost:8000/_snowpack/pkg/sudograph/build/sudo-playground.js:61004:22)\n    at async http://localhost:8000/_snowpack/pkg/sudograph/build/sudo-playground.js:61053:50"

**Comment by lastmjs** [comment]
What version exactly, 0.3.0? Make sure to check the canister-id attribute in your playground index.html file. The attribute should read `canister-id` and perhaps your id has changed for some reason

**Comment by webcoderz** [comment]
its 0.2.2 and the index.html canister-id attribute is saying the same canister id

**Comment by lastmjs** [comment]
I would try 0.3.0, but also make sure the canister id is actually correct, as in dfx may have changed them when you deployed again. `.dfx/local/canister_ids.json` should have them

**Comment by lastmjs** [comment]
Also what do you mean by the optimized version? Did you have to optimize your Wasm binary?

**Comment by webcoderz** [comment]
yea optimized binary, how do i do that without breaking dependencies? (i changed cargo.lock sudograph version to 0.3.0 in there and the sudograph canister cargo.toml, but now it adds ic_cdk 0.3.0 and gives me a dependency error

**Comment by webcoderz** [comment]
yea the optimized binary, i npm installed sudograph@0.3.0   and yarn but it keeps reverting to 0.2.2

**Comment by lastmjs** [comment]
Do you have this pushed to GitHub? I could probably easily spot the problem but it's hard to without the code.

In each canister, check the package.json and Cargo.toml files. Manually update the version to 0.3.0, by hand.

**Comment by lastmjs** [comment]
And make sure in your playground `index.html` file that `<sudo-playground canisterId="ryjl3-tyaaa-aaaaa-aaaba-cai"></sudo-playground>` is changed to `<sudo-playground canister-id="ryjl3-tyaaa-aaaaa-aaaba-cai"></sudo-playground>`, and make sure the canister id is correct

**Comment by webcoderz** [comment]
ok , i tried most of that as well: https://github.com/webi-ai/webi_api here is the code

**Comment by lastmjs** [comment]
Okay, I'm looking at the code

**Comment by lastmjs** [comment]
Change this https://github.com/webi-ai/webi_api/blob/main/canisters/graphql/Cargo.toml#L11 to `sudograph = "0.3.0"`

**Comment by lastmjs** [comment]
Change this https://github.com/webi-ai/webi_api/blob/main/canisters/playground/index.html to `<sudo-playground canister-id="ryjl3-tyaaa-aaaaa-aaaba-cai"></sudo-playground>`

**Comment by lastmjs** [comment]
Change this https://github.com/webi-ai/webi_api/blob/main/package.json#L7 to `"dfx-optimize-graphql": "./target/bin/ic-cdk-optimizer ./target/wasm32-unknown-unknown/release/graphql.wasm -o ./target/wasm32-unknown-unknown/release/graphql-optimized.wasm"`

This is probably your problem, there was a spelling mistake on `graphql-optimized.wasm`. Some of my examples had that wrong

**Comment by lastmjs** [comment]
And change this https://github.com/webi-ai/webi_api/blob/main/canisters/playground/package.json#L9 to `"sudograph": "0.3.0"`.

The top level package.json, https://github.com/webi-ai/webi_api/blob/main/package.json, shouldn't have any dependencies in it right now

**Comment by lastmjs** [comment]
Also, looking at your schema, the relations should look like more like this. Each side of the relation must have the same name:

```graphql
type URL {
    id: ID!
    url: String!
    map_asset_url: String!
    cities: [City!]! @relation(name: "URL:cities and City:map_location_url")
    countries: [Country!]! @relation(name: "URL:countries and Country:map_location_url")
}

type City {
    id: ID!
    city:  String!
    map_location_url: URL! @relation(name: "URL:cities and City:map_location_url")
}

type Country {
    id: ID!
    country:  String!
    map_location_url: URL! @relation(name: "URL:countries and Country:map_location_url")
}
```

**Comment by webcoderz** [comment]
ok cool that makes more sense, just pushed the changes didnt seem to build the graphql canister

**Comment by lastmjs** [comment]
If you're available I can do a video call

**Comment by lastmjs** [comment]
We got this sorted out, in `v0.3.0` of sudograph the playground canister id attributes were changed to `canister-id-local` and `canister-id-ic`
