### ISSUE TITLE
Cross-canister calls from within async-graphql will not work!!

### ISSUE THREAD

**Issue by lastmjs** [sudograph/sudograph#36]
- [x] I might need to fork ic_cdk to change a type, and hopefully they'll accept my pull request for a fix
- [x] UUID generation: To get this to be robust, I'll need to have this issues solved: async-graphql/async-graphql#110
- [x] I have not had success using DFINITY's async/await code from within an async mutation resolver...this issue really needs to be resolved, because cross-canister calls and perhaps many other IC features will not be accessible from within mutation resolvers until the above issue is resolved

**Comment by omarabid** [comment]
@lastmjs Hey, how did you fix this? I'm also developing for WASM and having a problem with these Send! futures.

**Comment by lastmjs** [comment]
The team fixed ic_cdk for me, quite a while ago now. I have not had any issues since, I assume using the latest version should work for you. Have you posted on form.dfinity.org?

**Comment by omarabid** [comment]
@lastmjs Thank you for your response but I am not using dfinity (don't really know what it is). I just happen that I have the same problem (trying to run a Send! future in async-graphql).
